<?php

namespace CatalogueBundle\Repository;

/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    
    public function findByWord($nom, $categorie) {

        $query = $this->createQueryBuilder('a')
        ->where('a.nom LIKE :key') ->AndWhere('a.categorie =:categorie')
        ->setParameter('key', '%'.$nom.'%')->setParameter('categorie',$categorie) -> getQuery();

        return $query->getResult();
    }
    
}
