<?php

namespace CatalogueBundle\Repository;

/**
 * MedicamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    
    public function findByWord($nom, $categorie) {

        $query = $this->createQueryBuilder('a')
        ->where('a.designation LIKE :key') ->AndWhere('a.medicament =:medicament')
        ->setParameter('key', '%'.$nom.'%')->setParameter('categorie',$categorie) -> getQuery();

        return $query->getResult();
    }
    
}
