user:
    resource: "@UserBundle/Resources/config/routing_user.yml"
    prefix:   /admin/user
    
    
catalogue_medicament:
    resource: "@CatalogueBundle/Resources/config/routing_medicament.yml"
    prefix:   /admin/medicament/
    
catalogue_client:
    resource: "@CatalogueBundle/Resources/config/routing_client.yml"
    prefix:   /admin/client/    
    
    
catalogue_fournisseur:
    resource: "@CatalogueBundle/Resources/config/routing_fournisseur.yml"
    prefix:   /admin/fournisseur/ 
    

app:
    resource: '@AppBundle/Controller/'
    type: annotation


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
